# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    schedule:
    - cron: '0 */12 * * *'
    workflow_dispatch:
  push:
    branches: 
    - "main"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
- name: Metrics embed
  uses: lowlighter/metrics@v3.24

